= SQL

* Structured Query Language

== Typen von SQL-Befehlen

SQL-Befehle werden in fünf Kategorien unterteilt:

* Data Definition Language (DDL)
* Data Query Language (DQL)
* Data Manipulation Language (DML)
* Data Control Language (DCL)
* Transaction Control Language (TCL)

=== Data Definition Language (DDL)

Die Befehle werden verwendet, um die Struktur des Datenbankschemas zu definieren.

* CREATE
* ALTER
* DROP
* TRUNCATE

=== Data Query Language (DQL)

Die Befehle werden verwendet, um Daten aus der Datenbank abzurufen.

*SELECT*

* wird verwendet, um Daten aus einer oder mehreren Tabellen in einer Datenbank abzurufen
* bietet eine Vielzahl von Funktionen zum Filtern, Sortieren und Gruppieren von Daten

[source,sql]
----
SELECT column1, column2, ... <1>
FROM table_name <2>
WHERE condition; <3>
----

<1> stehen für die Spalten der Tabelle
<2> ist der Name der Tabelle
<3> werden die Bedingungen angegeben, welche die Daten erfüllen müssen, um in die Ergebnismenge aufgenommen zu werden

.Filtering data
[source,sql]
----
SELECT *
FROM customers
WHERE city = 'New York';
----

.Sorting data
[source,sql]
----
SELECT *
FROM products
ORDER BY price DESC;
----

.Grouping data
[source,sql]
----
SELECT category, COUNT(*)
FROM products
GROUP BY category;
----

.Joining tables
[source,sql]
----
SELECT orders.order_id, customers.customer_name
FROM orders
JOIN customers
ON orders.customer_id = customers.customer_id;
----

=== Data Manipulation Language (DML)

Die Befehle werden verwendet, um Daten in der Datenbank zu ändern.

*INSERT*

* wird zum Einfügen neuer Zeilen von Daten in eine Tabelle verwendet

[source,sql]
----
INSERT INTO table_name (column1, column2, column3, ...) <1>
VALUES (value1, value2, value3, ...); <2>
----

<1> Name und Spalten der Tabelle, in der die Daten eingefügt werden sollen
<2> gibt die Werte an, die in jede Spalte eingefügt werden sollen

.Einfügen einer einzelnen Zeile
[source,sql]
----
INSERT INTO customers (customer_name, city, country)
VALUES('John Doe','New York','USA');
----

.Einfügen mehrerer Zeilen
[source,sql]
----
INSERT INTO orders (customer_id, product_id, quantity)
VALUES (1, 100, 2),
       (2, 200, 1),
       (3, 300, 3);
----

.Einfügen von Daten aus einer anderen Tabelle
[source,sql]
----
INSERT INTO new_customers (customer_name, city, country)
SELECT customer_name, city, country
FROM old_customers
WHERE country = 'USA';
----

* UPDATE

* dient dazu, vorhandene Zeilen an Daten in einer Tabelle zu ändern

[source,sql]
----
UPDATE table_name <1>
SET column1 = value1, column2 = value2, ... <2>
WHERE condition; <3>
----

<1> ist der Name der Tabelle, die Sie aktualisieren möchten
<2> stehen für die Spalten, die geändert werden sollen
<3> die neuen Werte für diese Spalten

.Aktualisierung einer einzelnen Zeile
[source,sql]
----
UPDATE customers
SET city = 'Los Angeles'
WHERE customer_id = 1;
----

.Aktualisierung mehrerer Zeilen
[source,sql]
----
UPDATE orders
SET status = 'shipped'
WHERE customer_id = 1;
----

.Aktualisierung von Daten auf der Basis einer anderen Tabelle
[source,sql]
----
UPDATE customers
SET city = new_addresses.city, country = new_addresses.country
FROM new_addresses
WHERE customers.customer_id = new_addresses.customer_id;
----

*DELETE*

* wird verwendet, um eine oder mehrere Zeilen von Daten aus einer Tabelle zu entfernen

[source,sql]
----
DELETE FROM table_name <1>
WHERE condition; <2>
----

<1> ist der Name der Tabelle, aus der Daten gelöscht werden sollen
<2> dient zur Angabe der Bedingungen, die die Daten erfüllen müssen, damit sie gelöscht werden können

.Löschen einer einzelnen Zeile
[source,sql]
----
DELETE FROM customers
WHERE customer_id = 1;
----

.Löschen von mehreren Zeilen
[source,sql]
----
DELETE FROM orders
WHERE customer_id = 1;
----

.Alle Zeilen aus einer Tabelle entfernen
[source,sql]
----
DELETE FROM customers;
----

.Löschen von Daten basierend auf einer anderen Tabelle
[source,sql]
----
DELETE FROM customers
WHERE customer_id IN (SELECT customer_id
                      FROM old_customers
                      WHERE country = 'USA');
----

=== Data Control Language (DCL)

Die Befehle werden verwendet, um den Zugang und die Berechtigungen von Benutzern auf der Datenbank zu kontrollieren.

* GRANT
* REVOKE

=== Transaction Control Language (TCL)

Die Befehle werden zur Verwaltung von Transaktionen in der Datenbank verwendet.

* COMMIT
* ROLLBACK
* SAVEPOINT